export enum InventoryReservationStatus {
  PENDING = "PENDING",
  RESERVED = "RESERVED",
  PARTIALLY_RESERVED = "PARTIALLY_RESERVED",
  FAILED = "FAILED",
  CONSUMED = "CONSUMED",
  RELEASED = "RELEASED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}
